import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "@/lib/StoreProvider";
import "./globals.css";
import dynamic from "next/dynamic";
import { Navbar } from "@/components/Navbar/Navbar";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { CssBaseline, Box } from '@mui/material';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const Loading = dynamic(() => import('./loading'), {
//   ssr: false 
   // Отключаем SSR для компонента Loading
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <div className="container">
            <Sidebar />
            <main>{children}</main>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
